name: Hello CI

on:
  push:
    branches:
      - week4/day24
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from CI/CD"

      - name: Show Python version
        run: python3 --version

      - name: Show working directory
        run: pwd && ls -la